### ISSUE TITLE
How do you add a yaml header?

### ISSUE THREAD

**Issue by cani-venatici** [kiwi0fruit/sugartex#6]
I'm trying to use sugartex to write an article but how do you add a yaml header? From the 'Usage' section I'm using this to render the pdf to which I added the last line:

```bash
#!/usr/bin/env bash
export PYTHONIOENCODING=utf-8

cat "$1".md | \
pre-sugartex | \
pandoc -f markdown -t json | \
sugartex --kiwi | \
pandoc -f json -o "$1".md.md | \
pandoc --pdf-engine=lualatex -F pandoc-eqnos -F sugartex -H "/path/head.tex" --number-sections -f markdown "$1".md.md -o "$1".pdf
```

However, I don't understand how to add a yaml header specifying parameters for LaTeX like title, author, date, margins, fonts, toc info.

1. Adding `-H  '/path/header.yml` to the last line exits with 'file has no `\begin{document}`'
2. Writing the yaml header directly into the source file `$1.md` has no effect as it doesn't get output in the pdf
3. Adding it, still through `-H  '/path/header.yml`, in `pandoc -f json -o "$1".md.md | \` doesn't seem to have any effect as it doesn't get included in the pdf or a tex file if I output to tex instead of pdf.

**Comment by kiwi0fruit** [comment]
If I remember correctly header is simply a part of the Markdown document so adding it directly to input document should be fine. If that doesn't work then the problem lies elsewhere.

But that's about **yaml** headers not **tex** headers (I know that yaml headers support title, author and toc). I know that tex can be added via template but I guess there might be other ways too. See [Pandoc Manual](https://pandoc.org/MANUAL.html) for how to specify yaml sections and add tex.

I also recommend to fix redundancy from the script as it seems to me that there is no need for double Pandoc pass:

```bash
#!/usr/bin/env bash
export PYTHONIOENCODING=utf-8

cat "$1" | pre-sugartex |
pandoc -f markdown --pdf-engine=lualatex --number-sections -F sugartex -F pandoc-eqnos -o "$1.pdf"
```
(I guess sugartex filter should be first - before pandoc-eqnos. By the way: pandoc-crossref filter can be used instead of pandoc-eqnos).

I removed `-H "/path/head.tex"` as I'm not sure if it works - please test yourself yaml headers and ways of adding tex first (I can help later but I never pandoc-exported to pdf via latex - I mostly use to docx export and to pdf via html).

By the way: you can `cat "$1" <(printf "\n\n") "header.yml"` to add header to the file without it.
